services:
  nginx:
    image: nginx:alpine
    container_name: nginx-puaas
    restart: always
    ports:
      - "9006:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: PayUs-as-a-Service
    working_dir: /var/www
    restart: always
    volumes:
      - ./:/var/www
    command: ["php-fpm"]

  mysql_puaas:
    image: mysql:latest
    container_name: mysql-puaas
    restart: always
    env_file:
      - .env.db